# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Tue Oct  3 17:56:57 2023
# ------------------------------------------------

package:
  name: pycosat
  version: 0.6.6
source:
  sha256: b0014986321e77a36d8fe24827698aae076500c817133a700608bd677b77a998
  url: https://github.com/conda/pycosat/archive/0.6.6.tar.gz
build:
  number: '0'
  script: /Users/runner/miniforge3/conda-bld/pycosat_1696355969704/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps -vv
  string: py310h2aa6e3c_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - cctools_osx-arm64 973.0.1 h2f5fd4a_14
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_3
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - cross-python_osx-arm64 3.10 41_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - gettext 0.21.1 h8a4c099_0
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 h0fd476b_14
    - ld64_osx-arm64 609 he51b688_14
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcxx 16.0.6 hd57cbcb_0
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_3
    - libsqlite 3.43.0 h58db7d2_0
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 15.0.7 he4b1e75_3
    - lz4-c 1.9.4 hf0c8a7f_0
    - ncurses 6.4 hf0c8a7f_0
    - openssl 3.1.3 h8a1eda9_0
    - popt 1.16 h7b079dc_2002
    - python 3.10.12 had23ca6_0_cpython
    - readline 8.2 h9e318b2_1
    - rsync 3.2.7 h30d983d_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.13 hef22860_0
    - tzdata 2023c h71feb2d_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2023.7.22 hf0a4a13_0
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.43.0 hb31c410_0
    - libzlib 1.2.13 h53f4e23_5
    - ncurses 6.4 h7ea286d_0
    - openssl 3.1.3 h53f4e23_0
    - pip 23.2.1 pyhd8ed1ab_0
    - python 3.10.12 h01493a6_0_cpython
    - readline 8.2 h92ec313_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - tk 8.6.13 hb31c410_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
  run:
    - python >=3.10,<3.11.0a0
    - python >=3.10,<3.11.0a0 *_cpython
    - python_abi 3.10.* *_cp310
test:
  commands:
    - pip check
    - python test_package.py "0.6.6"
  files:
    - qg3-08.cnf
    - sudoku.py
    - test_package.py
    - uf20-098.cnf
  imports:
    - pycosat
  requires:
    - pip
about:
  description: 'PicoSAT is a popular SAT solver written by Armin Biere in pure C.
    This

    package provides efficient Python bindings to picosat on the C level, i.e.

    when importing pycosat, the picosat solver becomes part of the Python

    process itself.

    '
  dev_url: https://github.com/conda/pycosat
  doc_source_url: https://github.com/conda/pycosat/blob/master/README.rst
  doc_url: https://pypi.python.org/pypi/pycosat
  home: https://github.com/conda/pycosat
  license: MIT
  license_file:
    - COPYRIGHT
    - LICENSE
  summary: Bindings to picosat (a SAT solver)
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - msarahan
    - nehaljwani
    - pelson
