# This file created by conda-build 24.3.0
# ------------------------------------------------

package:
  name: libcurl
  version: 8.7.1
source:
  sha256: 05bbd2b698e9cfbab477c33aa5e99b4975501835a41b7ca6ca71de03d8849e76
  url: http://curl.haxx.se/download/curl-8.7.1.tar.bz2
build:
  number: 0
  run_exports:
    - libcurl >=8.7.1,<9.0a0
  string: h2d989ff_0
requirements:
  build:
    - ca-certificates 2024.2.2 h8857fd0_0
    - cctools_osx-64 986 ha1c5b94_0
    - cctools_osx-arm64 986 h7bb7a8e_0
    - clang 16.0.6 hdae98eb_6
    - clang-16 16.0.6 default_h7151d67_6
    - clang_impl_osx-arm64 16.0.6 ha81d56d_11
    - clang_osx-arm64 16.0.6 h40be2b1_11
    - clangxx 16.0.6 default_h7151d67_6
    - compiler-rt 16.0.6 ha38d28d_2
    - compiler-rt_osx-64 16.0.6 ha38d28d_2
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 711 ha20a434_0
    - ld64_osx-arm64 711 h6aa3cc8_0
    - libclang-cpp16 16.0.6 default_h7151d67_6
    - libcxx 16.0.6 hd57cbcb_0
    - libiconv 1.17 hd75f5a5_2
    - libllvm16 16.0.6 hbedff68_3
    - libxml2 2.12.6 hc0ae0f7_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 16.0.6 hbedff68_3
    - openssl 3.2.1 hd75f5a5_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - c-ares 1.27.0 h93a5062_0
    - ca-certificates 2024.2.2 hf0a4a13_0
    - krb5 1.21.2 h92f50d5_0
    - libcxx 16.0.6 h4653b0c_0
    - libedit 3.1.20191231 hc8eb9b7_2
    - libev 4.33 h93a5062_2
    - libnghttp2 1.58.0 ha4dd798_1
    - libssh2 1.11.0 h7a5bd25_0
    - libzlib 1.2.13 h53f4e23_5
    - ncurses 6.4.20240210 h078ce10_0
    - openssl 3.2.1 h0d3ecfb_1
    - zlib 1.2.13 h53f4e23_5
    - zstd 1.5.5 h4f39d0f_0
  run:
    - krb5 >=1.21.2,<1.22.0a0
    - libnghttp2 >=1.58.0,<2.0a0
    - libssh2 >=1.11.0,<2.0a0
    - libzlib >=1.2.13,<1.3.0a0
    - openssl >=3.2.1,<4.0a0
    - zstd >=1.5.5,<1.6.0a0
test:
  commands:
    - curl-config --features
    - curl-config --protocols
    - test -f ${PREFIX}/lib/libcurl${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libcurl.a
    - CURL_SSL_BACKENDS=$(curl-config --ssl-backends)
    - if ! echo $CURL_SSL_BACKENDS | grep -q "OpenSSL"; then exit 1; fi
    - if ! echo $CURL_SSL_BACKENDS | grep -q "Secure Transport"; then exit 1; fi
about:
  description: 'Curl is an open source command line tool and library for transferring
    data

    with URL syntax. It is used in command lines or scripts to transfer data.

    '
  dev_url: https://github.com/curl/curl
  doc_source_url: https://github.com/curl/curl/tree/master/docs
  doc_url: https://curl.haxx.se/docs/
  home: http://curl.haxx.se/
  license: curl
  license_family: MIT
  license_file: COPYING
  summary: tool and library for transferring data with URL syntax
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240327.2.1
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - xylar
  remote_url: https://github.com/conda-forge/curl-feedstock
  sha: 3d6c4469eb66a73b74f9f457b7a63f8713829354
