# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Aug 17 16:29:25 2020
# ------------------------------------------------

package:
    name: lzo
    version: '2.10'
source:
    sha256: c0f892943208266f9b6543b3ae308fab6284c5c90e627931446fb49b4221a072
    url: http://www.oberhumer.com/opensource/lzo/download/lzo-2.10.tar.gz
build:
    number: '1000'
    run_exports:
        - lzo >=2.10,<3.0a0
    string: h642e427_1000
requirements:
    build:
        - bzip2 1.0.8 haf1e3a3_2
        - c-ares 1.16.1 haf1e3a3_0
        - ca-certificates 2020.6.20 hecda079_0
        - cctools_osx-arm64 949.0.1 ha30c52b_9
        - clang 11.0.0.rc1 default_hf57f61e_0
        - clang_osx-arm64 11.0.0.rc1 hd819f65_5
        - clangxx 11.0.0.rc1 default_hf57f61e_0
        - cmake 3.18.0 h9f6fb0d_0
        - compiler-rt 11.0.0.rc1 h810911b_0
        - compiler-rt_osx-64 11.0.0.rc1 h2a69e3a_0
        - expat 2.2.9 hb1e8313_2
        - krb5 1.17.1 h75d18d8_2
        - ld64_osx-arm64 530 h8c8ad8c_9
        - libclang-cpp11 11.0.0.rc1 default_hf57f61e_0
        - libcurl 7.71.1 he6690cf_4
        - libcxx 11.0.0.rc1 h5f48129_0
        - libedit 3.1.20191231 h0678c8f_2
        - libev 4.33 haf1e3a3_0
        - libllvm11 11.0.0.rc1 h009f743_3
        - libnghttp2 1.41.0 h8a08a2b_1
        - libssh2 1.9.0 h8a08a2b_5
        - libuv 1.38.0 h0b31af3_0
        - llvm-tools 11.0.0.rc1 h1341992_3
        - make 4.3 h0b31af3_0
        - ncurses 6.2 hb1e8313_1
        - openssl 1.1.1g haf1e3a3_1
        - rhash 1.3.6 h1de35cc_1001
        - tapi 1100.0.11 h879752b_0
        - tk 8.6.10 hb0a8c7a_0
        - xz 5.2.5 haf1e3a3_1
        - zlib 1.2.11 1007
test:
    commands:
        - test -f ${PREFIX}/include/lzo/lzoconf.h
        - test -f ${PREFIX}/lib/liblzo2.a
        - test -f ${PREFIX}/lib/liblzo2${SHLIB_EXT}
about:
    description: 'LZO offers pretty fast compression and extremely fast decompression.

        MiniLZO is a very lightweight subset of the LZO library.

        '
    home: http://www.oberhumer.com/opensource/lzo/
    license: GPL v2+
    license_family: GPL2
    license_file: COPYING
    summary: LZO is a portable lossless data compression library written in ANSI C.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - rmax
