# This file created by conda-build 3.28.3
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Jan 12 14:03:02 2024
# ------------------------------------------------

package:
  name: menuinst
  version: 2.0.2
source:
  sha256: 2846d3435b13375fe9242a985f355c176ace7a31072c230bdd5b0bfd13367701
  url: https://github.com/conda/menuinst/archive/2.0.2.tar.gz
build:
  number: '0'
  script:
    - /Users/runner/miniforge3/conda-bld/menuinst_1705068367719/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
      -m pip install . -vv
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION=2.0.2
  string: py310hbe9552e_0
requirements:
  build:
    - bzip2 1.0.8 h10d778d_5
    - ca-certificates 2023.11.17 h8857fd0_0
    - cctools_osx-64 973.0.1 h031c385_15
    - cctools_osx-arm64 973.0.1 h8d715a0_15
    - clang 17.0.6 hac416ee_2
    - clang-17 17.0.6 default_h6b1ee41_2
    - clang_impl_osx-arm64 17.0.6 h840ab8d_8
    - clang_osx-arm64 17.0.6 h40be2b1_8
    - clangxx 17.0.6 default_h6b1ee41_2
    - compiler-rt 17.0.6 ha38d28d_1
    - compiler-rt_osx-64 17.0.6 ha38d28d_1
    - cross-python_osx-arm64 3.10 41_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - gettext 0.21.1 h8a4c099_0
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 hd3532be_15
    - ld64_osx-arm64 609 hade76d1_15
    - libclang-cpp17 17.0.6 default_h6b1ee41_2
    - libcxx 16.0.6 hd57cbcb_0
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.17 hd75f5a5_2
    - libllvm17 17.0.6 hbedff68_1
    - libsqlite 3.44.2 h92b6c6a_0
    - libxml2 2.12.3 hc0ae0f7_0
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 17.0.6 hbedff68_1
    - lz4-c 1.9.4 hf0c8a7f_0
    - ncurses 6.4 h93d8f39_2
    - openssl 3.2.0 hd75f5a5_1
    - popt 1.16 h7b079dc_2002
    - python 3.10.13 h00d2728_1_cpython
    - readline 8.2 h9e318b2_1
    - rsync 3.2.7 h30d983d_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.13 h1abcd95_1
    - tzdata 2023d h0c530f3_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - bzip2 1.0.8 h93a5062_5
    - ca-certificates 2023.11.17 hf0a4a13_0
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.44.2 h091b4b1_0
    - libzlib 1.2.13 h53f4e23_5
    - ncurses 6.4 h463b476_2
    - openssl 3.2.0 h0d3ecfb_1
    - packaging 23.2 pyhd8ed1ab_0
    - pip 23.3.2 pyhd8ed1ab_0
    - python 3.10.13 h2469fbe_1_cpython
    - readline 8.2 h92ec313_1
    - setuptools 69.0.3 pyhd8ed1ab_0
    - setuptools-scm 8.0.4 pyhd8ed1ab_0
    - setuptools_scm 8.0.4 hd8ed1ab_0
    - tk 8.6.13 h5083fa2_1
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.9.0 hd8ed1ab_0
    - typing_extensions 4.9.0 pyha770c72_0
    - tzdata 2023d h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
  run:
    - python >=3.10,<3.11.0a0
    - python >=3.10,<3.11.0a0 *_cpython
    - python_abi 3.10.* *_cp310
test:
  commands:
    - SP_DIR="$(python -c 'import site; print(site.getsitepackages()[0])')"
    - test -f "${SP_DIR}/menuinst/data/appkit_launcher_arm64"
    - test -f "${SP_DIR}/menuinst/data/appkit_launcher_x86_64"
    - test -f "${SP_DIR}/menuinst/data/osx_launcher_arm64"
    - test -f "${SP_DIR}/menuinst/data/osx_launcher_x86_64"
  imports:
    - menuinst
    - menuinst.api
about:
  doc_url: https://conda.github.io/menuinst/
  home: https://github.com/conda/menuinst/
  license: BSD-3-Clause AND MIT
  license_file:
    - LICENSE.txt
    - menuinst/_vendor/apipkg/LICENSE
  summary: cross platform install of menu items
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240112.2.1
  recipe-maintainers:
    - carlodri
    - goanpeca
    - isuruf
    - jaimergp
    - jakirkham
  remote_url: https://github.com/conda-forge/menuinst-feedstock
  sha: 100bc037d6759541cb8e55194037ae1239f0c90b
