# This file created by conda-build 24.1.2
# ------------------------------------------------

package:
  name: libsqlite
  version: 3.45.2
source:
  patches: null
  sha256: bc9067442eedf3dd39989b5c5cfbfff37ae66cc9c99274e0c3052dc4d4a8f6ae
  url: https://www.sqlite.org/2024/sqlite-autoconf-3450200.tar.gz
build:
  number: 0
  run_exports:
    - libsqlite >=3.45.2,<4.0a0
  string: h091b4b1_0
requirements:
  build:
    - ca-certificates 2024.2.2 h8857fd0_0
    - cctools_osx-64 973.0.1 ha1c5b94_16
    - cctools_osx-arm64 973.0.1 h7bb7a8e_16
    - clang 16.0.6 hdae98eb_5
    - clang-16 16.0.6 default_h7151d67_5
    - clang_impl_osx-arm64 16.0.6 ha81d56d_10
    - clang_osx-arm64 16.0.6 h40be2b1_10
    - clangxx 16.0.6 default_h7151d67_5
    - compiler-rt 16.0.6 ha38d28d_2
    - compiler-rt_osx-64 16.0.6 ha38d28d_2
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 ha20a434_16
    - ld64_osx-arm64 609 h6aa3cc8_16
    - libclang-cpp16 16.0.6 default_h7151d67_5
    - libcxx 16.0.6 hd57cbcb_0
    - libiconv 1.17 hd75f5a5_2
    - libllvm16 16.0.6 hbedff68_3
    - libtool 2.4.7 hf0c8a7f_0
    - libxml2 2.12.5 hc0ae0f7_0
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 16.0.6 hbedff68_3
    - make 4.3 h22f3db7_1
    - openssl 3.2.1 hd75f5a5_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - libzlib 1.2.13 h53f4e23_5
    - zlib 1.2.13 h53f4e23_5
  run:
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libsqlite3.a
    - test -f $PREFIX/include/sqlite3.h
    - test -f $PREFIX/include/sqlite3ext.h
about:
  description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

    public-domain, SQL database engine.It is the most used database engine

    in the world.

    '
  dev_url: https://github.com/mackyle/sqlite
  doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
  doc_url: http://www.sqlite.org/docs.html
  home: http://www.sqlite.org/
  license: Unlicense
  license_url: http://www.sqlite.org/copyright.html
  summary: Implements a self-contained, zero-configuration, SQL database engine
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240312.2.1
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
  remote_url: https://github.com/conda-forge/sqlite-feedstock
  sha: 54d530b057e4faf0e1b592479609b94fcf2fa022
