# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: reproc
  version: 14.2.4.post0
source:
  - patches:
      - 103-remove-fd-limit.patch
      - apple_gettime.patch
    sha256: 55c780f7faa5c8cabd83ebbb84b68e5e0e09732de70a129f6b3c801e905415dd
    url: https://github.com/DaanDeMeyer/reproc/archive/v14.2.4.tar.gz
build:
  number: 1
  run_exports:
    - reproc >=14.2,<15.0a0
  string: h93a5062_1
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.20.1 h10d778d_1
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 ha1c5b94_15
    - cctools_osx-arm64 973.0.1 h7bb7a8e_15
    - clang 16.0.6 hc177806_1
    - clang-16 16.0.6 default_h762fdd7_1
    - clang_impl_osx-arm64 16.0.6 ha81d56d_6
    - clang_osx-arm64 16.0.6 h40be2b1_6
    - clangxx 16.0.6 default_h762fdd7_1
    - cmake 3.27.6 hf40c264_0
    - compiler-rt 16.0.6 he1888fc_1
    - compiler-rt_osx-64 16.0.6 he1888fc_1
    - icu 73.2 hf5e326d_0
    - krb5 1.21.2 hb884880_0
    - ld64_osx-64 609 ha20a434_15
    - ld64_osx-arm64 609 h6aa3cc8_15
    - libclang-cpp16 16.0.6 default_h762fdd7_1
    - libcurl 8.4.0 h726d00d_0
    - libcxx 16.0.6 hd57cbcb_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libexpat 2.5.0 hf0c8a7f_1
    - libiconv 1.17 hac89ed1_0
    - libllvm16 16.0.6 he4b1e75_2
    - libnghttp2 1.52.0 he2ab024_0
    - libssh2 1.11.0 hd019ec5_0
    - libuv 1.46.0 h0c2f820_0
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 16.0.6 he4b1e75_2
    - ncurses 6.4 hf0c8a7f_0
    - ninja 1.11.1 hb8565cd_0
    - openssl 3.1.4 hd75f5a5_0
    - rhash 1.4.4 h0dc2134_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  run: []
test:
  commands:
    - test -f ${PREFIX}/include/reproc/run.h
    - test -f ${PREFIX}/lib/libreproc${SHLIB_EXT}
    - test -f ${PREFIX}/lib/cmake/reproc/reproc-config.cmake
    - test ! -f ${PREFIX}/include/reproc++/run.hpp
    - test ! -f ${PREFIX}/lib/libreproc++${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libreproc.a
    - test ! -f ${PREFIX}/lib/libreproc++.a
    - test ! -f ${PREFIX}/lib/cmake/reproc++/reproc++-config.cmake
    - cmake -G Ninja -S test-c/ -B build-test-c/ ${CMAKE_ARGS}
    - cmake --build build-test-c/
    - cmake --build build-test-c/ --target test
  files:
    - test-c/
  requires:
    - clang_osx-arm64 16.*
    - cmake
    - ninja
about:
  dev_url: https://github.com/DaanDeMeyer/reproc
  home: https://github.com/DaanDeMeyer/reproc
  license: MIT
  license_file: LICENSE
  summary: reproc (Redirected Process) is a cross-platform C/C++ library that simplifies
    starting, stopping and communicating with external programs.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - AntoinePrv
    - DaanDeMeyer
    - wolfv
