# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Nov  6 14:09:48 2023
# ------------------------------------------------

package:
  name: bzip2
  version: 1.0.8
source:
  patches:
    - 0001-cross.patch
  sha256: ab5a03176ee106d3f0fa90e381da478ddae405918153cca248e682cd0c4a2269
  url: https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz
build:
  number: '5'
  run_exports:
    - bzip2 >=1.0.8,<2.0a0
  string: h93a5062_5
requirements:
  build:
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 ha1c5b94_15
    - cctools_osx-arm64 973.0.1 h7bb7a8e_15
    - clang 16.0.6 hc177806_1
    - clang-16 16.0.6 default_h762fdd7_1
    - clang_impl_osx-arm64 16.0.6 ha81d56d_6
    - clang_osx-arm64 16.0.6 h40be2b1_6
    - clangxx 16.0.6 default_h762fdd7_1
    - compiler-rt 16.0.6 he1888fc_1
    - compiler-rt_osx-64 16.0.6 he1888fc_1
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 ha20a434_15
    - ld64_osx-arm64 609 h6aa3cc8_15
    - libclang-cpp16 16.0.6 default_h762fdd7_1
    - libcxx 16.0.6 hd57cbcb_0
    - libiconv 1.17 hac89ed1_0
    - libllvm16 16.0.6 he4b1e75_2
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 16.0.6 he4b1e75_2
    - make 4.3 h22f3db7_1
    - openssl 3.1.4 hd75f5a5_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  run: []
test:
  commands:
    - bzip2 --help
    - test -f ${PREFIX}/bin/bunzip2
    - test -f ${PREFIX}/bin/bzcat
    - test -f ${PREFIX}/bin/bzcmp
    - test -f ${PREFIX}/bin/bzdiff
    - test -f ${PREFIX}/bin/bzegrep
    - test -f ${PREFIX}/bin/bzfgrep
    - test -f ${PREFIX}/bin/bzgrep
    - test -f ${PREFIX}/bin/bzip2recover
    - test -f ${PREFIX}/bin/bzip2
    - test -f ${PREFIX}/bin/bzless
    - test -f ${PREFIX}/bin/bzmore
    - test -f ${PREFIX}/include/bzlib.h
    - test -f ${PREFIX}/lib/libbz2.a
    - test -f ${PREFIX}/lib/libbz2.dylib
about:
  description: 'Bzip2 is a freely available high-quality data compressor. It typically

    compresses files to within 10% to 15% of the best available techniques,

    whilst being around twice as fast at compression and six times faster

    at decompression.

    '
  doc_url: http://www.bzip.org/docs.html
  home: http://www.bzip.org/
  license: bzip2-1.0.6
  license_family: BSD
  license_file: LICENSE
  summary: high-quality data compressor
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - jakirkham
    - jlanga
    - msarahan
    - pelson
