# This file created by conda-build 3.28.1
# ------------------------------------------------

package:
  name: libnghttp2
  version: 1.58.0
source:
  sha256: 9ebdfbfbca164ef72bdf5fd2a94a4e6dfb54ec39d2ef249aeb750a91ae361dfb
  url: https://github.com/nghttp2/nghttp2/releases/download/v1.58.0/nghttp2-1.58.0.tar.gz
build:
  number: 1
  run_exports:
    - libnghttp2 >=1.58.0,<2.0a0
  string: ha4dd798_1
requirements:
  build:
    - ca-certificates 2023.11.17 h8857fd0_0
    - cctools_osx-64 973.0.1 ha1c5b94_15
    - cctools_osx-arm64 973.0.1 h7bb7a8e_15
    - clang 16.0.6 hac416ee_3
    - clang-16 16.0.6 default_h6b1ee41_3
    - clang_impl_osx-arm64 16.0.6 ha81d56d_6
    - clang_osx-arm64 16.0.6 h40be2b1_6
    - clangxx 16.0.6 default_h6b1ee41_3
    - clangxx_impl_osx-arm64 16.0.6 hf982f3f_6
    - clangxx_osx-arm64 16.0.6 h072c24e_6
    - compiler-rt 16.0.6 ha38d28d_2
    - compiler-rt_osx-64 16.0.6 ha38d28d_2
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 ha20a434_15
    - ld64_osx-arm64 609 h6aa3cc8_15
    - libclang-cpp16 16.0.6 default_h6b1ee41_3
    - libcxx 16.0.6 hd57cbcb_0
    - libiconv 1.17 hac89ed1_0
    - libllvm16 16.0.6 hbedff68_3
    - libxml2 2.12.2 hc0ae0f7_0
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 16.0.6 hbedff68_3
    - make 4.3 h22f3db7_1
    - openssl 3.2.0 hd75f5a5_1
    - pkg-config 0.29.2 ha3d46e9_1008
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - c-ares 1.23.0 h93a5062_0
    - ca-certificates 2023.11.17 hf0a4a13_0
    - libcxx 16.0.6 h4653b0c_0
    - libev 4.33 h642e427_1
    - libzlib 1.2.13 h53f4e23_5
    - openssl 3.2.0 h0d3ecfb_1
    - zlib 1.2.13 h53f4e23_5
  run:
    - __osx >=10.9
    - c-ares >=1.23.0,<2.0a0
    - libcxx >=16.0.6
    - libev >=4.33,<4.34.0a0
    - libev >=4.33,<5.0a0
    - libzlib >=1.2.13,<1.3.0a0
    - openssl >=3.2.0,<4.0a0
test:
  commands:
    - nghttp -nv https://nghttp2.org
    - test ! -f ${PREFIX}/lib/libnghttp2.a
about:
  description: 'This is an implementation of the Hypertext Transfer Protocol version
    2 in C.


    The framing layer of HTTP/2 is implemented as a reusable C library. On top

    of that, we have implemented an HTTP/2 client, server and proxy. We have

    also developed load test and benchmarking tools for HTTP/2.

    '
  dev_url: https://github.com/nghttp2/nghttp2
  doc_url: https://nghttp2.org/documentation/
  home: http://github.com/nghttp2/nghttp2
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: This is an implementation of Hypertext Transfer Protocol version 2.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20231209.1.1
  recipe-maintainers:
    - cpaulik
    - mariusvniekerk
    - wolfv
  remote_url: https://github.com/conda-forge/nghttp2-feedstock
  sha: efe866398bb7adce64d594174bd53f6a3acc6d2e
