# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Nov  1 09:13:35 2023
# ------------------------------------------------

package:
  name: zstandard
  version: 0.22.0
source:
  sha256: 8226a33c542bcb54cd6bd0a366067b610b41713b64c9abec1bc4533d69f51e70
  url: https://pypi.io/packages/source/z/zstandard/zstandard-0.22.0.tar.gz
build:
  number: '0'
  string: py310h6289e41_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 ha1c5b94_15
    - cctools_osx-arm64 973.0.1 h7bb7a8e_15
    - cffi 1.16.0 py310hdca579f_0
    - clang 16.0.6 hc177806_1
    - clang-16 16.0.6 default_h762fdd7_1
    - clang_impl_osx-arm64 16.0.6 ha81d56d_6
    - clang_osx-arm64 16.0.6 h40be2b1_6
    - clangxx 16.0.6 default_h762fdd7_1
    - compiler-rt 16.0.6 he1888fc_1
    - compiler-rt_osx-64 16.0.6 he1888fc_1
    - cross-python_osx-arm64 3.10 41_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - gettext 0.21.1 h8a4c099_0
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 ha20a434_15
    - ld64_osx-arm64 609 h6aa3cc8_15
    - libclang-cpp16 16.0.6 default_h762fdd7_1
    - libcxx 16.0.6 hd57cbcb_0
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.17 hac89ed1_0
    - libllvm16 16.0.6 he4b1e75_2
    - libsqlite 3.43.2 h92b6c6a_0
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 16.0.6 he4b1e75_2
    - lz4-c 1.9.4 hf0c8a7f_0
    - ncurses 6.4 h93d8f39_2
    - openssl 3.1.4 hd75f5a5_0
    - popt 1.16 h7b079dc_2002
    - pycparser 2.21 pyhd8ed1ab_0
    - python 3.10.13 h00d2728_0_cpython
    - python_abi 3.10 4_cp310
    - readline 8.2 h9e318b2_1
    - rsync 3.2.7 h30d983d_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.13 hef22860_0
    - tzdata 2023c h71feb2d_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2023.7.22 hf0a4a13_0
    - cffi 1.16.0 py310hdcd7c05_0
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.43.2 h091b4b1_0
    - libzlib 1.2.13 h53f4e23_5
    - ncurses 6.4 h463b476_2
    - openssl 3.1.4 h0d3ecfb_0
    - pip 23.3.1 pyhd8ed1ab_0
    - pycparser 2.21 pyhd8ed1ab_0
    - python 3.10.13 h2469fbe_0_cpython
    - python_abi 3.10 4_cp310
    - readline 8.2 h92ec313_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - tk 8.6.13 hb31c410_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.3 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
    - zstd 1.5.5 h4f39d0f_0
  run:
    - cffi >=1.11
    - python >=3.10,<3.11.0a0
    - python >=3.10,<3.11.0a0 *_cpython
    - python_abi 3.10.* *_cp310
    - zstd >=1.5.5,<1.5.6.0a0
    - zstd >=1.5.5,<1.6.0a0
test:
  commands:
    - pip check
  imports:
    - zstandard
  requires:
    - pip
about:
  description: 'This project provides Python bindings for interfacing with the

    Zstandard compression library. A C extension and CFFI interface are

    provided.

    '
  dev_url: https://github.com/indygreg/python-zstandard
  doc_url: https://github.com/indygreg/python-zstandard/blob/master/README.rst#python-zstandard
  home: https://github.com/indygreg/python-zstandard
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Zstandard bindings for Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - pavelzw
    - rmax
    - xhochy
