# This file created by conda-build 3.26.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Sep  8 06:28:44 2023
# ------------------------------------------------

package:
  name: truststore
  version: 0.8.0
source:
  sha256: dc70da89634944a579bfeec70a7a4523c53ffdb3cf52d1bb4a431fda278ddb96
  url: https://pypi.io/packages/source/t/truststore/truststore-0.8.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/truststore_1694154605758/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2023.7.22 hbcca054_0
    - flit-core 3.9.0 pyhd8ed1ab_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.1.0 he5830b7_0
    - libgomp 13.1.0 he5830b7_0
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.43.0 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.2 hd590300_0
    - pip 23.2.1 pyhd8ed1ab_0
    - python 3.11.5 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 68.1.2 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.10
test:
  commands:
    - pip check
  imports:
    - truststore
  requires:
    - pip
about:
  dev_url: https://github.com/sethmlarson/truststore
  doc_url: https://truststore.readthedocs.io/en/latest/
  home: https://github.com/sethmlarson/truststore
  license: MIT
  license_file: LICENSE
  summary: Verify certificates using native system trust stores
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - wolfv
