# This file created by conda-build 3.28.4
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Feb  7 14:01:39 2024
# ------------------------------------------------

package:
  name: ruamel.yaml.clib
  version: 0.2.8
source:
  - sha256: beb2e0404003de9a4cab9753a8805a8fe9320ee6673136ed7f04255fe60bb512
    url: https://pypi.io/packages/source/r/ruamel.yaml.clib/ruamel.yaml.clib-0.2.8.tar.gz
  - fn: _ruamel_yaml.pyx
    patches:
      - fix-typecasts-s390x._ruamel_yaml.pyx.patch
    sha256: fb6b5653201f1ed89a951f6931fda377737156c4f30cadbd240f4d28f607665a
    url: https://sourceforge.net/p/ruamel-yaml-clib/code/ci/0.2.8/tree/_ruamel_yaml.pyx?format=raw
  - fn: _ruamel_yaml.pxd
    patches:
      - fix-typecasts-s390x._ruamel_yaml.pxd.patch
    sha256: ee35a75fd753a369bee439ec7e1826e77c7feaabf9c3ec9cf2f58110c7a95656
    url: https://sourceforge.net/p/ruamel-yaml-clib/code/ci/0.2.8/tree/_ruamel_yaml.pxd?format=raw
build:
  number: '0'
  script:
    - cythonize _ruamel_yaml.pyx
    - /Users/runner/miniforge3/conda-bld/ruamel.yaml.clib_1707314852085/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
      -m pip install . -vv
  string: py310hd125d64_0
requirements:
  build:
    - bzip2 1.0.8 h10d778d_5
    - ca-certificates 2024.2.2 h8857fd0_0
    - cctools_osx-64 973.0.1 ha1c5b94_16
    - cctools_osx-arm64 973.0.1 h7bb7a8e_16
    - clang 16.0.6 hdae98eb_5
    - clang-16 16.0.6 default_h7151d67_5
    - clang_impl_osx-arm64 16.0.6 ha81d56d_9
    - clang_osx-arm64 16.0.6 h40be2b1_9
    - clangxx 16.0.6 default_h7151d67_5
    - compiler-rt 16.0.6 ha38d28d_2
    - compiler-rt_osx-64 16.0.6 ha38d28d_2
    - cross-python_osx-arm64 3.10 41_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - cython 0.29.37 py310h5daac23_0
    - gettext 0.21.1 h8a4c099_0
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 ha20a434_16
    - ld64_osx-arm64 609 h6aa3cc8_16
    - libclang-cpp16 16.0.6 default_h7151d67_5
    - libcxx 16.0.6 hd57cbcb_0
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.17 hd75f5a5_2
    - libllvm16 16.0.6 hbedff68_3
    - libsqlite 3.44.2 h92b6c6a_0
    - libxml2 2.12.5 hc0ae0f7_0
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 16.0.6 hbedff68_3
    - lz4-c 1.9.4 hf0c8a7f_0
    - ncurses 6.4 h93d8f39_2
    - openssl 3.2.1 hd75f5a5_0
    - popt 1.16 h7b079dc_2002
    - python 3.10.13 h00d2728_1_cpython
    - python_abi 3.10 4_cp310
    - readline 8.2 h9e318b2_1
    - rsync 3.2.7 h30d983d_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.13 h1abcd95_1
    - tzdata 2024a h0c530f3_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - bzip2 1.0.8 h93a5062_5
    - ca-certificates 2024.2.2 hf0a4a13_0
    - cython 0.29.37 py310h692a8b6_0
    - libcxx 16.0.6 h4653b0c_0
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.44.2 h091b4b1_0
    - libzlib 1.2.13 h53f4e23_5
    - ncurses 6.4 h463b476_2
    - openssl 3.2.1 h0d3ecfb_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.10.13 h2469fbe_1_cpython
    - python_abi 3.10 4_cp310
    - readline 8.2 h92ec313_1
    - setuptools 69.0.3 pyhd8ed1ab_0
    - tk 8.6.13 h5083fa2_1
    - tzdata 2024a h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
  run:
    - python >=3.10,<3.11.0a0
    - python >=3.10,<3.11.0a0 *_cpython
    - python_abi 3.10.* *_cp310
test:
  commands:
    - python -c "from importlib.util import find_spec; assert find_spec('_ruamel_yaml')"
  downstreams:
    - ruamel.yaml
about:
  home: https://sourceforge.net/projects/ruamel-yaml-clib/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: C version of reader, parser and emitter for ruamel.yaml derived from libyaml
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240207.3.1
  recipe-maintainers:
    - mbargull
    - ocefpaf
  remote_url: https://github.com/conda-forge/ruamel.yaml.clib-feedstock
  sha: 275b106d20ed84e5a55c4e726a766d2c60abfde8
