CI: azure
CONDA_BUILD_SYSROOT: /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
MACOSX_DEPLOYMENT_TARGET: '11.0'
VERBOSE_AT: V=1
build_platform: osx-64
c_compiler: clang_bootstrap
c_compiler_version: '16'
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: clang_bootstrap
extend_keys:
- ignore_build_only_deps
- pin_run_as_build
- ignore_version
- extend_keys
fortran_compiler: gfortran
icu: '73'
ignore_build_only_deps:
- numpy
- python
libiconv: '1'
lua: '5'
macos_machine: arm64-apple-darwin20.0.0
numpy: '1.22'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
python: '3.10'
r_base: '3.5'
target_platform: osx-arm64
xz: '5'
zlib: '1.2'
