# This file created by conda-build 3.28.1
# ------------------------------------------------

package:
  name: libarchive
  version: 3.7.2
source:
  patches:
    - patches/0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
    - patches/0003-VC9-compatibility-test-for-BCryptDeriveKeyPBKDF2.patch
    - patches/0004-VC9-compatibility-define-BCRYPT_SUCCESS.patch
    - patches/0006-VC-openssl-define-inline-as-__inline.patch
    - patches/0007-CMake-VC9-compatibility-ignore-some-warnings.patch
  sha256: 63b40acff57467f7d3a64981d4bcff60b52f539fae7688aaaaee27a448b10266
  url: https://github.com/libarchive/libarchive/archive/v3.7.2.tar.gz
build:
  number: 1
  run_exports:
    - libarchive >=3.7.2,<3.8.0a0
  string: hcacb583_1
requirements:
  build:
    - autoconf 2.71 pl5321hed12c24_1
    - automake 1.16.5 pl5321h694c41f_0
    - ca-certificates 2023.11.17 h8857fd0_0
    - cctools_osx-64 973.0.1 ha1c5b94_15
    - cctools_osx-arm64 973.0.1 h7bb7a8e_15
    - clang 16.0.6 hac416ee_3
    - clang-16 16.0.6 default_h6b1ee41_3
    - clang_impl_osx-arm64 16.0.6 ha81d56d_6
    - clang_osx-arm64 16.0.6 h40be2b1_6
    - clangxx 16.0.6 default_h6b1ee41_3
    - compiler-rt 16.0.6 ha38d28d_2
    - compiler-rt_osx-64 16.0.6 ha38d28d_2
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 ha20a434_15
    - ld64_osx-arm64 609 h6aa3cc8_15
    - libclang-cpp16 16.0.6 default_h6b1ee41_3
    - libcxx 16.0.6 hd57cbcb_0
    - libiconv 1.17 hac89ed1_0
    - libllvm16 16.0.6 hbedff68_3
    - libtool 2.4.7 hf0c8a7f_0
    - libxml2 2.12.2 hc0ae0f7_0
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 16.0.6 hbedff68_3
    - m4 1.4.18 haf1e3a3_1001
    - make 4.3 h22f3db7_1
    - openssl 3.2.0 hd75f5a5_1
    - perl 5.32.1 4_h0dc2134_perl5
    - pkg-config 0.29.2 ha3d46e9_1008
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - bzip2 1.0.8 h93a5062_5
    - ca-certificates 2023.11.17 hf0a4a13_0
    - icu 73.2 hc8870d7_0
    - libcxx 16.0.6 h4653b0c_0
    - libiconv 1.17 he4db4b2_0
    - libxml2 2.12.2 h0d0cfa8_0
    - libzlib 1.2.13 h53f4e23_5
    - lz4-c 1.9.3 hbdafb3b_1
    - lzo 2.10 h642e427_1000
    - openssl 3.2.0 h0d3ecfb_1
    - xz 5.2.6 h57fd34a_0
    - zlib 1.2.13 h53f4e23_5
    - zstd 1.5.5 h4f39d0f_0
  run:
    - bzip2 >=1.0.8,<2.0a0
    - libiconv >=1.17,<2.0a0
    - libxml2 >=2.12.2,<2.13.0a0
    - libzlib >=1.2.13,<1.3.0a0
    - lz4-c >=1.9.3,<1.10.0a0
    - lzo >=2.10,<3.0a0
    - openssl >=3.2.0,<4.0a0
    - xz >=5.2.6,<6.0a0
    - zstd >=1.5.5,<1.6.0a0
test:
  commands:
    - test -f "${PREFIX}/lib/pkgconfig/libarchive.pc"
    - test -f "${PREFIX}/include/archive.h"
    - test -f "${PREFIX}/include/archive_entry.h"
    - test -f "${PREFIX}/lib/libarchive.a"
    - test -f "${PREFIX}/lib/libarchive${SHLIB_EXT}"
    - bsdcat --version
    - bsdcpio --version
    - bsdtar --version
    - bsdtar -tf test/hello_world.xar
  files:
    - test/hello_world.xar
about:
  home: http://www.libarchive.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING
  summary: Multi-format archive and compression library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20231207.1.1
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
  remote_url: https://github.com/conda-forge/libarchive-feedstock
  sha: c2a74d760c2b32adae32b11c930f1c04c4692925
