# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sat Mar 30 17:21:06 2024
# ------------------------------------------------

package:
  name: c-ares
  version: 1.28.1
source:
  sha256: 675a69fc54ddbf42e6830bc671eeb6cd89eeca43828eb413243fd2c0a760809d
  url: https://c-ares.haxx.se/download/c-ares-1.28.1.tar.gz
build:
  number: '0'
  run_exports:
    - c-ares >=1.28.1,<2.0a0
  string: h93a5062_0
requirements:
  build:
    - ca-certificates 2024.2.2 h8857fd0_0
    - cctools_osx-64 986 ha1c5b94_0
    - cctools_osx-arm64 986 h7bb7a8e_0
    - clang 16.0.6 hdae98eb_6
    - clang-16 16.0.6 default_h7151d67_6
    - clang_impl_osx-arm64 16.0.6 ha81d56d_11
    - clang_osx-arm64 16.0.6 h40be2b1_11
    - clangxx 16.0.6 default_h7151d67_6
    - cmake-no-system 3.29.0 h73e2aa4_0
    - compiler-rt 16.0.6 ha38d28d_2
    - compiler-rt_osx-64 16.0.6 ha38d28d_2
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 711 ha20a434_0
    - ld64_osx-arm64 711 h6aa3cc8_0
    - libclang-cpp16 16.0.6 default_h7151d67_6
    - libcxx 16.0.6 hd57cbcb_0
    - libiconv 1.17 hd75f5a5_2
    - libllvm16 16.0.6 hbedff68_3
    - libxml2 2.12.6 hc0ae0f7_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 16.0.6 hbedff68_3
    - ninja 1.11.1 hb8565cd_0
    - openssl 3.2.1 hd75f5a5_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  run: []
  run_constraint:
    - c-ares-static <0a0
about:
  home: https://c-ares.haxx.se/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: This is c-ares, an asynchronous resolver library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240330.2.1
  recipe-maintainers:
    - ocefpaf
    - wesm
    - xhochy
  remote_url: https://github.com/conda-forge/c-ares-feedstock
  sha: 67cd1d46854f72f025fa69260b8bb5d73db17da1
