# This file created by conda-build 3.28.2
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Jan  5 11:32:57 2024
# ------------------------------------------------

package:
  name: fmt
  version: 10.2.1
source:
  sha256: 1250e4cc58bf06ee631567523f48848dc4596133e163f02615c97f78bab6c811
  url: https://github.com/fmtlib/fmt/archive/10.2.1.tar.gz
build:
  number: '0'
  run_exports:
    - fmt >=10.2.1,<11.0a0
  string: h2ffa867_0
requirements:
  build:
    - bzip2 1.0.8 h10d778d_5
    - c-ares 1.24.0 h10d778d_0
    - ca-certificates 2023.11.17 h8857fd0_0
    - cctools_osx-64 973.0.1 ha1c5b94_15
    - cctools_osx-arm64 973.0.1 h7bb7a8e_15
    - clang 16.0.6 hac416ee_4
    - clang-16 16.0.6 default_h6b1ee41_4
    - clang_impl_osx-arm64 16.0.6 ha81d56d_8
    - clang_osx-arm64 16.0.6 h40be2b1_8
    - clangxx 16.0.6 default_h6b1ee41_4
    - clangxx_impl_osx-arm64 16.0.6 h4a79b72_8
    - clangxx_osx-arm64 16.0.6 h40be2b1_8
    - cmake 3.28.1 h7c85d92_0
    - compiler-rt 16.0.6 ha38d28d_2
    - compiler-rt_osx-64 16.0.6 ha38d28d_2
    - icu 73.2 hf5e326d_0
    - krb5 1.21.2 hb884880_0
    - ld64_osx-64 609 ha20a434_15
    - ld64_osx-arm64 609 h6aa3cc8_15
    - libclang-cpp16 16.0.6 default_h6b1ee41_4
    - libcurl 8.5.0 h726d00d_0
    - libcxx 16.0.6 hd57cbcb_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 h10d778d_2
    - libexpat 2.5.0 hf0c8a7f_1
    - libiconv 1.17 hd75f5a5_2
    - libllvm16 16.0.6 hbedff68_3
    - libnghttp2 1.58.0 h64cf6d3_1
    - libssh2 1.11.0 hd019ec5_0
    - libuv 1.46.0 h0c2f820_0
    - libxml2 2.12.3 hc0ae0f7_0
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 16.0.6 hbedff68_3
    - make 4.3 h22f3db7_1
    - ncurses 6.4 h93d8f39_2
    - openssl 3.2.0 hd75f5a5_1
    - rhash 1.4.4 h0dc2134_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - libcxx 16.0.6 h4653b0c_0
  run:
    - libcxx >=15
test:
  commands:
    - test -d ${PREFIX}/include/fmt
    - test -f ${PREFIX}/include/fmt/core.h
    - test -f ${PREFIX}/include/fmt/format.h
    - test -f ${PREFIX}/lib/cmake/fmt/fmt-config.cmake
    - test -f ${PREFIX}/lib/libfmt.dylib
  downstreams:
    - libmambapy
about:
  description: '{fmt} is an open-source formatting library for C++.

    It can be used as a safe and fast alternative to (s)printf and iostreams.

    '
  dev_url: https://github.com/fmtlib/fmt
  doc_url: https://fmt.dev/latest/
  home: https://fmt.dev/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: '{fmt} is an open-source formatting library for C++'
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240105.1.1
  recipe-maintainers:
    - bdice
    - saraedum
    - tdegeus
    - vitaut
  remote_url: https://github.com/conda-forge/fmt-feedstock
  sha: 5a482aad8e93053196cfed83402a6a4c0addce8c
