# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: brotli-python
  version: 1.1.0
source:
  fn: brotli-1.1.0.tar.gz
  sha256: e720a6ca29428b803f4ad165371771f5398faba397edf6778837a18599ea13ff
  url: https://github.com/google/brotli/archive/v1.1.0.tar.gz
build:
  ignore_run_exports_from:
    - brotli
  number: 1
  string: py310h1253130_1
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.19.1 h0dc2134_0
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - cctools_osx-arm64 973.0.1 h2f5fd4a_14
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_3
    - clangxx_osx-arm64 15.0.7 hc662a55_3
    - cmake 3.27.6 hf40c264_0
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - cross-python_osx-arm64 3.10 41_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - gettext 0.21.1 h8a4c099_0
    - icu 73.2 hf5e326d_0
    - krb5 1.21.2 hb884880_0
    - ld64_osx-64 609 h0fd476b_14
    - ld64_osx-arm64 609 he51b688_14
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcurl 8.3.0 h5f667d7_0
    - libcxx 16.0.6 hd57cbcb_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libexpat 2.5.0 hf0c8a7f_1
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_3
    - libnghttp2 1.52.0 he2ab024_0
    - libsqlite 3.43.0 h58db7d2_0
    - libssh2 1.11.0 hd019ec5_0
    - libuv 1.46.0 h0c2f820_0
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 15.0.7 he4b1e75_3
    - lz4-c 1.9.4 hf0c8a7f_0
    - ncurses 6.4 hf0c8a7f_0
    - ninja 1.11.1 hb8565cd_0
    - openssl 3.1.3 h8a1eda9_0
    - popt 1.16 h7b079dc_2002
    - python 3.10.12 had23ca6_0_cpython
    - readline 8.2 h9e318b2_1
    - rhash 1.4.4 h0dc2134_0
    - rsync 3.2.7 h30d983d_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.13 hef22860_0
    - tzdata 2023c h71feb2d_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - brotli 1.1.0 hb547adb_1
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2023.7.22 hf0a4a13_0
    - libcxx 16.0.6 h4653b0c_0
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.43.0 hb31c410_0
    - libzlib 1.2.13 h53f4e23_5
    - ncurses 6.4 h7ea286d_0
    - openssl 3.1.3 h53f4e23_0
    - pip 23.2.1 pyhd8ed1ab_0
    - python 3.10.12 h01493a6_0_cpython
    - readline 8.2 h92ec313_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - tk 8.6.13 hb31c410_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
  run:
    - libcxx >=15.0.7
    - python >=3.10,<3.11.0a0
    - python >=3.10,<3.11.0a0 *_cpython
    - python_abi 3.10.* *_cp310
  run_constrained:
    - libbrotlicommon 1.1.0 hb547adb_1
test:
  imports:
    - brotli
about:
  home: http://github.com/google/brotli
  license: MIT
  license_file: LICENSE
  summary: Brotli compression format
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - CJ-Wright
    - wesm
    - xhochy
